version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: fintracker
      POSTGRES_USER: finuser
      POSTGRES_PASSWORD: finpass
    ports:
      - "5433:5432"